config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  devise_for :users


  resources :clinics, only: [ :index, :new, :create ]


  resources :exams do
    resources :timeslots, only: [ :new, :create, :edit, :update ]
  end

  resources :timeslots, only: [ :show ] do
    resources :bookings, only: [ :new, :create, :show ]
  end

  resources :bookings, only: [ :show, :edit, :update, :destroy ] do
    resources :results, only: [ :new, :create, :show, :index ]
    resources :chatrooms, only: :show do
      resources :messages, only: :create
    end
  end

  get "dashboard", to: "users#dashboard", as: "dashboard"



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  # :confirmable
  #rest of the code
  has_many :bookings, dependent: :destroy
  has_many :chatrooms, dependent: :destroy
  has_one_attached :photo

  validates :title, presence: true
  validates :full_name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :birthday, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: :dashboard
  def dashboard
    @user = current_user

    if current_user.admin
      @users = User.all.reject{ |user| user.bookings.empty?}
      # @booking = Booking.find(params[:id])
      @bookings = Booking.all
    end
  end

  def photo

  end
end

app/views/users/dashboard.html.erb
<br><h1 id="dashboard-header"><strong><%= @current_user.full_name %>'s Dashboard</strong></h1>
<div class="container-dashboard">
  <div class="dashboard-left">
    <div class="dashboard-profile">
          <img id="profile-pic"> <%= cl_image_tag @current_user.photo.key, height: 200, width: 200, border_radius: 50 %><br> <img>
          <div class="profile-info">
            <h3 id="dashboard-subs-profile"><strong>Profile</strong></h3>
            <h6><strong><%= @current_user.full_name %></strong><h6>
            <br><%= @current_user.address %><br>
            <%= @current_user.email %><br>
            <%= @current_user.phone_number %><br>
            <%= @current_user.birthday %><br>
          </div>
    </div>

    <div class="video-advice">
      <div class="advice">
        <h3 id="dashboard-subs"><strong>Advice</strong></h3>
        <h6 id="breast-info"><strong> How to Do a Self Breast Exam </strong><h6>
        <iframe class="breast-video" width="600" height="400" src="https://www.youtube.com/embed/bO8nleSz8YA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
    </div>
  </div>

  <div class="next-booking">
    <h3 id="dashboard-subs-booking"><strong>Bookings</strong></h3>
    <div class="bookings-card">
      <% if current_user.admin %>
      <div class="admin-card">
          <% @users.each do |user| %>

            <%= user.title %> <%= user.full_name %>
            <%= user.address %>

            <% user.bookings.each do |booking| %>
            <h6> <strong><%= booking.timeslot.exam.service%>: <%= booking.timeslot.exam.body_part %></strong> </h6><br>
            <strong><%= booking.timeslot.exam.clinic.name %></strong>
            <%= booking.timeslot.exam.clinic.address %> <br>
            <%= booking.timeslot.date.to_formatted_s(:short) %> <br>
            <strong>Paid:</strong> £<%= booking.timeslot.exam.price %> <br>

              <%= simple_form_for [booking] do |f| %>
              <%= f.check_box :confirmed %>
              <%= f.submit "Submit" %>
              <% end %>

              <%= link_to "Add Result", new_booking_result_path(booking) %>
              <p style="color: #000000"><%= link_to "", booking_path(booking),
                  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
                  class:"fa-solid fa-trash"%>
              </p>

              <div class="result-bookings">
                  <div><h6 style="color: #515AE9;"><strong><%= link_to "View Results", booking_results_path(booking) %></strong></h6>
                  </div>
              </div>

              <h6 style="color: #5354F2"><strong>Message Patient</strong> <%= link_to " ", booking_chatroom_path(booking, booking.chatroom.id),class:"fa-solid fa-envelope" %>

            <% end %>
          <% end %>
      </div>

        <% else %>
          <div class="user-card">
            <% current_user.bookings.each do |booking| %>
              <div class="upcoming-bookings">


                <div class="scan-header">
                  <br><h5> <strong><%= booking.timeslot.exam.service%>: <%= booking.timeslot.exam.body_part %></strong> </h5>
                </div>

                <div class="booking-content">
                  <div class="booking-left">
                    <div class="clinic-info-booking">
                      <strong><%= booking.timeslot.exam.clinic.name %></strong><br>
                      <%= booking.timeslot.exam.clinic.address %> <br>
                      <strong>Date:</strong> <%= booking.timeslot.date.to_formatted_s(:short) %> <br>
                      <strong>Paid:</strong> £<%= booking.timeslot.exam.price %> <br>
                    </div><br>

                    <div class="booking-status">
                    <strong>Booking Status:</strong>
                    <% if booking.confirmed == true %>
                      <h6 style="color: green;">Booking Confirmed by the Clinic!</h6><br>
                    <% else %>
                      <h6 style="color: #EA9B0F;">Booking Confirmation is Pending. Please wait for the clinic to confirm.</h6><br>
                    <% end %>
                    </div>

                  </div>

                  <div class="booking-right">
                    <div class="result-bookings">
                      <% if booking.results.present? %>
                        <button class="result-btn" style="text-decoration-none" type="submit"><%= link_to("Your Results", booking_results_path(booking)) %></button>
                      <% end %>
                    </div>

                    <div class="message-clinic">
                      <button class="message-btn" style="text-decoration-none" type="submit"><%= link_to("Message Clinic", booking_chatroom_path(booking, booking.chatroom.id)) %></button>
                    </div>

                  </div>

                  </div>
                    <p class="delete-button" style="color: #000000"><%= link_to "", booking_path(booking),
                      data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
                      class:"fa-solid fa-trash"%>
                    </p>
                  </div>
                </div>


            <% end %>
          </div>

        <% end %>
    </div>
  </div>
</div>

app/views/users/test.html copy.erb
<br><h1 id="dashboard-header"><strong><%= @current_user.full_name %>'s Dashboard</strong></h1>
<div class="container-dashboard">
  <div class="dashboard-left">
    <div class="dashboard-profile">
      <div class="profile-left">
        <h3 id="dashboard-subs"><strong>Profile</strong></h3>
        <h6><strong><%= @current_user.full_name %></strong><h6>
        <img id="profile-pic"> <%= cl_image_tag @current_user.photo.key, height: 200, width: 200, crop: :fill %><br> <img>
        <br><%= @current_user.address %><br>
        <%= @current_user.email %><br>
        <%= @current_user.phone_number %><br>
        <%= @current_user.birthday %><br>
      </div>

      <div class="next-booking">
        <h3 id="dashboard-subs"><strong>Bookings</strong></h3>
        <div class="bookings-card">
          <% if current_user.admin %>
          <div class="admin-card">
              <% @users.each do |user| %>

                <%= user.title %> <%= user.full_name %>
                <%= user.address %>

                <% user.bookings.each do |booking| %>
                <h6> <strong><%= booking.timeslot.exam.service%>: <%= booking.timeslot.exam.body_part %></strong> </h6><br>
                <strong><%= booking.timeslot.exam.clinic.name %></strong>
                <%= booking.timeslot.exam.clinic.address %> <br>
                <%= booking.timeslot.date.to_formatted_s(:short) %> <br>
                <strong>Paid:</strong> £<%= booking.timeslot.exam.price %> <br>

                  <%= simple_form_for [booking] do |f| %>
                  <%= f.check_box :confirmed %>
                  <%= f.submit "Submit" %>
                  <% end %>

                  <div class="result-bookings">
                      <div><h6 style="color: #515AE9"><strong>Results</strong></h6>
                      </div>
                  </div>
                <% end %>
              <% end %>
          </div>

            <% else %>
              <div class="user-card">
                <% current_user.bookings.each do |booking| %>
                  <div class="upcoming-bookings">
                    <br><h5> <strong><%= booking.timeslot.exam.service%>: <%= booking.timeslot.exam.body_part %></strong> </h5><br>
                    <strong><%= booking.timeslot.exam.clinic.name %></strong>
                    <%= booking.timeslot.exam.clinic.address %> <br>
                    <%= booking.timeslot.date.to_formatted_s(:short) %> <br>
                    <strong>Paid:</strong> £<%= booking.timeslot.exam.price %> <br>

                    <strong>Booking Status:</strong> <%= booking.confirmed %> <br>

                    <%= booking.confirmed %> <br>

                    <div class="reschedule-booking">
                      <p> <strong> <#%link_to("Reschedule Booking", edit_exam_timeslot_path(booking.timeslot), class: "edit-btn") %></strong></p>
                    </div>
                    <div class="result-bookings">
                      <div><h6 style="color: #515AE9"><strong>Results</strong></h6>
                        <%# <% if booking.result.documents.attached? %>
                          <%# <% booking.result.documents.each do |document| %>
                            <%#= image_tag document %>
                            <%# if document.previewable? %>
                              <%#= image_tag(document.preview(resize: '200x200')) %>
                            <%# end %>
                          <%# end %>
                        <%# end %>
                      </div>


                      <p style="color: #000000"><%= link_to "", booking_path(booking),
                        data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
                        class:"fa-solid fa-trash"%>
                      </p>
                    </div>
                  </div>
                <% end %>
              </div>

            <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="video-advice">
    <div class="advice">
      <h3 id="dashboard-subs"><strong>Advice</strong></h3>
      <iframe width="1000" height="630" src="https://www.youtube.com/embed/bO8nleSz8YA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>
  </div>
</div>