config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  devise_for :users


  resources :clinics, only: [ :index, :new, :create ]


  resources :exams do
    resources :timeslots, only: [ :new, :create, :edit, :update ]
  end

  resources :timeslots, only: [ :show ] do
    resources :bookings, only: [ :new, :create, :show ]
  end

  resources :bookings, only: [ :show, :edit, :update, :destroy ] do
    resources :results, only: [ :new, :create, :show, :index ]
    resources :chatrooms, only: :show do
      resources :messages, only: :create
    end
  end

  get "dashboard", to: "users#dashboard", as: "dashboard"



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/pages/home.html.erb
<div class="mask-group-div" data-controller="collections" data-collections-hash-value="<%= @body_part_services.to_json %>" style="background-image: url('<%= asset_url 'FINALbackground.png' %>')">
  <div class="homepage-img">
    <div class="form-home">
      <%= simple_form_for :exam, url: clinics_path, method: :get do |f| %>
        <h6><strong>Body Area<%= f.input :body_part, label: false, placeholder: "Body Area", collection: Exam::BODY_PART, data: { collections_target: "body-parts" }  %></strong></h6>
        <h6><strong>Scan Type<%= f.input :service, label: false, placeholder: "Scan Type", collection: Exam::SERVICE, input_html: { data: { action: 'change->collections#updateForm'} } %></strong></h6>
        <%= f.fields_for :clinic do |clinic_form| %>
          <h6><strong>Location<%= clinic_form.input :address, label: false, placeholder: "Enter Your Location",
          input_html: {data: {address_autocomplete_target: "address"}},
          wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}%></strong></h6>
        <% end %>
        <br>
        <%= f.submit "Find Clinics", class: "btn-7" %>
      <% end %>
    </div>
    <div class="where-women-can-get-answers-in">
      <h1 id="logo-home"><strong>scan</strong><i style="color: #515AE9";><strong>Her.</i></strong></h1>
      <h2 class="subtitle-home"><strong>Where women can get answers in</strong><i style="color: #EC656E";><strong> days </i></strong><strong>not months</strong></h2>
    </div>
    <b class="how-it-works">How it works</b>
    <b class="scanning-services-b">Scanning Services</b>


        <div class="page-contain">
          <a href="#" class="data-card">
            <h3>Step 1</h3>
            <h4><strong>Booking and Faster Referral</strong></h4>
            <p><strong>Select a scan type in a location that is convenient for you.</strong></p>
            <span class="link-text">
              <p>Back to Top</p>
            </span>
          </a>
        </div>
        <div class="page-contain1">
          <a href="#" class="data-card">
            <h3>Step 2</h3>
            <h4><strong>Scan Confirmation</strong></h4>
            <p><strong>Your chosen clinic will offer a choice of appointment times.</strong></p>
            <span class="link-text">
              <p>Back to Top</p>
            </span>
          </a>
        </div>
        <div class="page-contain2">
          <a href="#" class="data-card">
            <h3>Step 3</h3>
            <h4><strong>Your Appointment</strong></h4>
            <p><strong>The specialists at the selected clinic will answer any queries and complete the scan.</strong></p>
            <span class="link-text">
              <p>Back to Top</p>
            </span>
          </a>
        </div>
        <div class="page-contain3">
          <a href="#" class="data-card">
            <h3>Step 4</h3>
            <h4><strong>Your Results</strong></h4>
            <p><strong>Your clinician will receive your results within 7 days, and share your results via email.</strong></p>
            <span class="link-text">
              <p>Back to Top</p>
            </span>
          </a>
        </div>
      <div class="clinic-middle-card card-height">
        <a href="https://www.nhs.uk/conditions/ultrasound-scan/" class="data-card" target="_blank">
          <h6>Ultrasound</h6>
          <h4>Start from £180</h4>
          <p>A procedure that uses high-frequency sound waves to create an image of part of the inside of the body.</p>
          <span class="link-text">
            <p class="m-2">Click for more information</p>
            <svg width="25" height="16" viewBox="0 0 25 16" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" clip-rule="evenodd" d="M17.8631 0.929124L24.2271 7.29308C24.6176 7.68361 24.6176 8.31677 24.2271 8.7073L17.8631 15.0713C17.4726 15.4618 16.8394 15.4618 16.4489 15.0713C16.0584 14.6807 16.0584 14.0476 16.4489 13.657L21.1058 9.00019H0.47998V7.00019H21.1058L16.4489 2.34334C16.0584 1.95281 16.0584 1.31965 16.4489 0.929124C16.8394 0.538599 17.4726 0.538599 17.8631 0.929124Z" fill="#753BBD"/>
            </svg>
          </span>

        </a>
      </div>
      <div class="clinic-middle-card1 card-height">
        <a href="https://www.nhs.uk/conditions/ct-scan/" class="data-card" target="_blank">
          <h6>CT</h6>
          <h4>Start from £350</h4>
          <p>A computerised tomography (CT) scan uses X-rays and a computer to create detailed images of the inside of the body.</p>
          <span class="link-text">
            <p class="m-2">Click for more information</p>
            <svg width="25" height="16" viewBox="0 0 25 16" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" clip-rule="evenodd" d="M17.8631 0.929124L24.2271 7.29308C24.6176 7.68361 24.6176 8.31677 24.2271 8.7073L17.8631 15.0713C17.4726 15.4618 16.8394 15.4618 16.4489 15.0713C16.0584 14.6807 16.0584 14.0476 16.4489 13.657L21.1058 9.00019H0.47998V7.00019H21.1058L16.4489 2.34334C16.0584 1.95281 16.0584 1.31965 16.4489 0.929124C16.8394 0.538599 17.4726 0.538599 17.8631 0.929124Z" fill="#753BBD"/>
            </svg>
          </span>
        </a>
      </div>
      <div class="clinic-middle-card2 card-height">
        <a href="https://www.nhs.uk/pregnancy/your-pregnancy-care/screening-tests" class="data-card" target="_blank">
          <h6>Pregnancy</h6>
          <h4>Start from £120</h4>
          <p>Ultrasound scans use sound waves to build a picture of the baby in the womb. The scans are painless, and can be carried out at any stage of pregnancy.</p>
          <span class="link-text">
            <p class="m-2">Click for more information</p>
            <svg width="25" height="16" viewBox="0 0 25 16" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" clip-rule="evenodd" d="M17.8631 0.929124L24.2271 7.29308C24.6176 7.68361 24.6176 8.31677 24.2271 8.7073L17.8631 15.0713C17.4726 15.4618 16.8394 15.4618 16.4489 15.0713C16.0584 14.6807 16.0584 14.0476 16.4489 13.657L21.1058 9.00019H0.47998V7.00019H21.1058L16.4489 2.34334C16.0584 1.95281 16.0584 1.31965 16.4489 0.929124C16.8394 0.538599 17.4726 0.538599 17.8631 0.929124Z" fill="#753BBD"/>
            </svg>
          </span>
        </a>
      </div>
      <div class="clinic-middle-card3 card-height">
        <a href="https://www.nhs.uk/conditions/mri-scan/" class="data-card" target="_blank">
          <h6>MRI</h6>
          <h4>Start from £300</h4>
          <p>Magnetic Resonance Imaging uses strong magnetic fields and radio waves to produce detailed images of the inside of the body.</p>
          <span class="link-text">
            <p class="m-2">Click for more information</p>
            <svg width="25" height="16" viewBox="0 0 25 16" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" clip-rule="evenodd" d="M17.8631 0.929124L24.2271 7.29308C24.6176 7.68361 24.6176 8.31677 24.2271 8.7073L17.8631 15.0713C17.4726 15.4618 16.8394 15.4618 16.4489 15.0713C16.0584 14.6807 16.0584 14.0476 16.4489 13.657L21.1058 9.00019H0.47998V7.00019H21.1058L16.4489 2.34334C16.0584 1.95281 16.0584 1.31965 16.4489 0.929124C16.8394 0.538599 17.4726 0.538599 17.8631 0.929124Z" fill="#753BBD"/>
            </svg>
          </span>
        </a>
      </div>

    </div>
    <div class="shine-a-light-on-your-reproduc">
      <p class="shine-a-light-on-your-reproduc1">
        <span><span><strong>Shine a light on your reproductive health</strong></span>
        <span class="span"> </span></span>
      </p>
      <p class="search-for-mri-ct-ultrasound">
        <span><span>Search for MRI, CT, ultrasound and pregnancy scans near you and book an appointment online in minutes.</span></span>
      </p>
    </div>
    <div class="three-appointments-wrapped-up">
      Three appointments wrapped up into one, easy-to-use platform with
      dedicated guidance.
    </div>
    <a href="#" class="to-top scroll">Back to top</a>


        <div class="reviews-b">
        <b>Reviews</b>
              <div class="carousel-wrapper">
        <div class="carousel-container">
          <div class="carousel">
            <div class="image-one"></div>
            <div class="image-two"></div>
            <div class="image-three"></div>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>


<script>
  var clinicCardContainer = document.getElementById("clinicCardContainer");
  if (clinicCardContainer) {
    clinicCardContainer.addEventListener("click", function (e) {
      // Please sync "Info Page" to the project
    });
  }
  var clinicCardContainer1 = document.getElementById("clinicCardContainer1");
  if (clinicCardContainer1) {
    clinicCardContainer1.addEventListener("click", function (e) {
      // Please sync "Info Page" to the project
    });
  }
  var clinicCardContainer2 = document.getElementById("clinicCardContainer2");
  if (clinicCardContainer2) {
    clinicCardContainer2.addEventListener("click", function (e) {
      // Please sync "Info Page" to the project
    });
  }
  var clinicCardContainer3 = document.getElementById("clinicCardContainer3");
  if (clinicCardContainer3) {
    clinicCardContainer3.addEventListener("click", function (e) {
      // Please sync "Info Page" to the project
    });
  }
  </script>