config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  devise_for :users


  resources :clinics, only: [ :index, :new, :create ]


  resources :exams do
    resources :timeslots, only: [ :new, :create, :edit, :update ]
  end

  resources :timeslots, only: [ :show ] do
    resources :bookings, only: [ :new, :create, :show ]
  end

  resources :bookings, only: [ :show, :edit, :update, :destroy ] do
    resources :results, only: [ :new, :create, :show, :index ]
    resources :chatrooms, only: :show do
      resources :messages, only: :create
    end
  end

  get "dashboard", to: "users#dashboard", as: "dashboard"



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/timeslot.rb
class Timeslot < ApplicationRecord
  belongs_to :exam
  has_many :bookings, dependent: :destroy
end

app/controllers/timeslots_controller.rb
class TimeslotsController < ApplicationController

  def index
    @exams = Exam.all
    @timeslots = Timeslot.all
  end

  def show
    @exam = Exam.find(params[:exam_id])
    @timeslot = Timeslot.find(params[:id])
  end

  def new
    @exam = Exam.find(params[:exam_id])
    @timeslot = Timeslot.new
  end

  def create
    @exam = Exam.find(params[:exam_id])
    @timeslot = Timeslot.new(timeslot_params)
    @timeslot.exam = @exam
    if @timeslot.save
      redirect_to dashboard_path(current_user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @timeslot = Timeslot.where(current_user.timeslot.id)
  end

  def update
    @timeslot = Timeslot.find(params[:id])
    @timeslot.update(timeslot_params)
    redirect_to dashboard_path(current_user)
  end

  private

  def timeslot_params
    params.require(:timeslot).permit(:date, :exam_id)
  end
end

app/views/timeslots/edit.html.erb
<div class="clinics-container">
  <br><h1 class="clinics-title mb-3 mx-3" style="color: #ed636e;"><strong> Reschdule Booking</h1></strong>
  <br><h2 class="clinics-title mb-3 mx-3" style="color: #000000;"><strong> Select a new timeslot</h2></strong>
  <div class="row m-0">
    <div class="col-6">
      <% @clinics.each do |clinic| %>
          <div class="card shadow rounded-4 border mb-3">
            <div class="row m-0 mb-2">
              <div class="clinic-info">
                <div class="col-12">
                  <h3><strong><li class="list-unstyled mb-1" style="color: #ed636e;"><%= clinic.name %></li></strong></h3>
                  <% clinic.filtered_exams(params).each do |exam| %>
                    <ul class="list-unstyled">
                      <li class="mt-2"><strong>Scan Type: </strong><%= exam.service %></li>
                      <li><strong>Body Area: </strong><%= exam.body_part %></li>
                    </ul>
                  </div>

                <div class="clinic-pricing">
                  <h4 class="mt-2" style=""><strong>£<%= exam.price %></strong></h4>
                </div>
              </div>

                <div class="buttons">
                  <div class="config-button">
                    <div class="flex-container mb-2">
                      <% exam.timeslots.each do |timeslot| %>
                        <a href="<%= new_timeslot_booking_path(timeslot) %>" class="btn effect04 mb-3" data-sm-link-text="BOOK"><span><%=timeslot.date.to_formatted_s(:short)%></span></a>
                      <% end %>
                    </div>
                  </div>
                </div>
              <% end %>

            <div class="col-6 p-0">
              <div class="" style="background-image: url(<%= asset_path 'clinic.png' %>); height: 100%; width: 100%; object-fit: cover;"></div>
              <%#=link_to image_tag "clinic.jpeg", class: "" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col">
      <div id="map rounded-4 shadow" style="position: sticky; top: 10px;">
        <div>
          <div style="width: 100%; height: 97vh;"
            data-controller="map"
            data-map-markers-value="<%= @markers.to_json %>"
            data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<%# <div class="col-6 "> %>
  <%# <div class="" style="background-image: url(= asset_path 'clinic.jpeg'); height: 100%; width: 100%; object-fit: cover;"></div> %>
  <%#=link_to image_tag "clinic.jpeg", class: "" %>
<%# </div> %>

<%# <%= link_to(
  timeslot.date.to_formatted_s(:short),
  new_timeslot_booking_path(timeslot),
) %>

app/views/timeslots/new.html.erb
<h1>New Timeslot</h1>
<%= simple_form_for [@exam, @timeslot] do |f| %>
  <%= f.input :date, as: :datetime, html5: true  %>
  <%= f.submit "Add Timeslot", class: "btn btn-primary" %>
   <%= link_to "Back to homepage", root_path %>
<% end %>